---
title: "Kaisu's education"
author: ""
date: ""
output:
  html_document:
    theme: null
    css: "css/bootstrap.min.css"
    highlight: tango   # Code highlighting style
    toc: false         # Table of contents disabled for a simple front page
    toc_float: false
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```
```{=html}

<head>
  <title>Kaisu Hiltunen - Education</title>
  <link rel="stylesheet" href="css/bootstrap.min.css">
</head>

```

```{r, echo=FALSE, results="asis"}
#  Importing the Navigation bar and some styling
htmltools::includeHTML("css/navbar.html")
```

```{=html}
<!DOCTYPE html>
<html lang="en">
<head>
<div class="container" style="margin-top: 40px;">
    <div class="col-md-12"> 
        <h2>Education</h2>
      
      <h5 class="subtitle">Master of Science in Life Science Technologies,  Major in Bioinformation Technology and Digital Health</h5> 
      <p><em>Aalto University, School of Science</em></p>
      
      <p>  My master’s program combined advanced studies in biology, data science, and digital health technologies. I gained insights in analyzing biological data, developing computational models, and applying digital solutions to improve healthcare outcomes. These studies provided me with the tools to bridge the gap between technology and life sciences. 
      </p>
      
      <h5 class="subtitle">Bachelor of Science in Bioinformation Technology</h5>
      <p><em>Aalto University, School of Electrical Engineering</em></p>

      <p>During my bachelor’s studies, I focused on computer science, engineering, and biology. The curriculum emphasized the integration of information technology with biological research, equipping me with skills in data analysis, programming, and problem-solving in the context of life sciences.</p>
    </div>
</div>
<body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.min.js"></script>
</body>
</html>

```

