---
title: "Kaisu's projects"
author: ""
date: ""
output:
  html_document:
    theme: null
    css: "css/bootstrap.min.css"
    highlight: tango   # Code highlighting style
    toc: false         # Table of contents disabled for a simple front page
    toc_float: false
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```
```{=html}

<head>
  <title>Kaisu Hiltunen - Projects</title>
</head>

```

```{r, echo=FALSE, results="asis"}
#  Importing the Navigation bar and some styling
htmltools::includeHTML("css/navbar.html")
```

```{=html}
<!DOCTYPE html>
<html lang="en">
<head>
<div class="container" style="margin-top: 40px;">
    <div class="col-md-12"> 
        <h2>Projects</h2>
        <p>Below are some of the projects I maintain on GitHub. Click the headers to learn more:</p>

        <h4><a href="https://kaisuh.github.io/Emotion-AI/" target="_blank">Emotion AI</a></h4>
        <ul>
            <li>Building a CNN to identify emotions from images</li>
            <li>GitHub link: <a href="https://github.com/KaisuH/Emotion-AI" target="_blank">https://github.com/KaisuH/Emotion-AI</a></li>
        </ul>
        
        
        <h4><a href="https://kaisuh.github.io/brain-tumor-detector/" target="_blank">Brain tumor detector</a></h4>
        <ul>
            <li>Detecting and localising cancer tumors from MRI images with AI.</li>
            <li>GitHub link: <a href="https://github.com/KaisuH/Emotion-AI" target="_blank">https://github.com/KaisuH/brain-tumor-detector</a></li>
        </ul>
    </div>
</div>

</html>

```

